version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-inertia-app
    container_name: laravel-inertia-app
    restart: unless-stopped
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_TIMEZONE: ${APP_TIMEZONE}
      APP_URL: ${APP_URL}
    volumes:
      - .:/var/www/html
    expose:
      - "${PHP_PORT}" # PHP-FPM port exposed to the network

  nginx:
    image: nginx:latest
    container_name: nginx-web
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80" # Map the environment variable port
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
